# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: detect-private-key
      - id: pretty-format-json
      - id: sort-simple-yaml
        files: ^.*\.ya?ml$
      - id: check-yaml
        args: [--allow-multiple-documents]
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
  - repo: https://github.com/boozt-platform/pre-commit-hooks
    rev: feat-add-markdown-generator
    hooks:
      - id: shellcheck
