formatter: "markdown table"
version: ""
header-from: "docs/header.md"
footer-from: "docs/footer.md"
sections:
  hide: []
  show: []
content: |
  {{ .Header }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ include "docs/body.md" }}
  {{ .Outputs }}
  {{ .Footer }}
output:
  file: README1.md
  mode: replace
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: ""
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
